// REQUIRE DEPENDENCIES
// ============================================================
var mongoose = require('mongoose');
// DEFINE SCHEMA
// ============================================================
var skillsSchema = mongoose.Schema({
    name: {
        type: String,
        required: true
    },
    Barbarian: {
        type: Boolean,
        required: true
    },
    Bard: {
        type: Boolean,
        required: true
    },
    Cleric: {
        type: Boolean,
        required: true
    },
    Druid: {
        type: Boolean,
        required: true
    },
    Fighter: {
        type: Boolean,
        required: true
    },
    Monk: {
        type: Boolean,
        required: true
    },
    Paladin: {
        type: Boolean,
        required: true
    },
    Ranger: {
        type: Boolean,
        required: true
    },
    Rogue: {
        type: Boolean,
        required: true
    },
    Sorcerer: {
        type: Boolean,
        required: true
    },
    Wizard: {
        type: Boolean,
        required: true
    },
    Untrained: {
        type: Boolean,
        required: true
    },
    Ability: {
        type: String,
        required: true
    },
    ArmorCheck: {
        type: Boolean,
        required: true
    },
    description: {
        type: String,
        required: false
    }
});
// EXPORT SCHEMA
// ============================================================
module.exports = mongoose.model('Skills', skillsSchema);

// [
//   {
//     "Skill": "Acrobatics",
//     "Barbarian": "TRUE",
//     "Bard": "TRUE",
//     "Cleric": "FALSE",
//     "Druid": "FALSE",
//     "Fighter": "FALSE",
//     "Monk": "TRUE",
//     "Paladin": "FALSE",
//     "Ranger": "FALSE",
//     "Rogue": "TRUE",
//     "Sorcerer": "FALSE",
//     "Wizard": "FALSE",
//     "Untrained": "TRUE",
//     "Ability": "Dex",
//     "ArmorCheck": "TRUE"
//   },
//   {
//     "Skill": "Appraise",
//     "Barbarian": "FALSE",
//     "Bard": "TRUE",
//     "Cleric": "TRUE",
//     "Druid": "FALSE",
//     "Fighter": "FALSE",
//     "Monk": "FALSE",
//     "Paladin": "FALSE",
//     "Ranger": "FALSE",
//     "Rogue": "TRUE",
//     "Sorcerer": "TRUE",
//     "Wizard": "TRUE",
//     "Untrained": "TRUE",
//     "Ability": "Int",
//     "ArmorCheck": "FALSE"
//   },
//   {
//     "Skill": "Bluff",
//     "Barbarian": "FALSE",
//     "Bard": "TRUE",
//     "Cleric": "FALSE",
//     "Druid": "FALSE",
//     "Fighter": "FALSE",
//     "Monk": "FALSE",
//     "Paladin": "FALSE",
//     "Ranger": "FALSE",
//     "Rogue": "TRUE",
//     "Sorcerer": "TRUE",
//     "Wizard": "FALSE",
//     "Untrained": "TRUE",
//     "Ability": "Cha",
//     "ArmorCheck": "FALSE"
//   },
//   {
//     "Skill": "Climb",
//     "Barbarian": "TRUE",
//     "Bard": "TRUE",
//     "Cleric": "FALSE",
//     "Druid": "TRUE",
//     "Fighter": "TRUE",
//     "Monk": "TRUE",
//     "Paladin": "FALSE",
//     "Ranger": "TRUE",
//     "Rogue": "TRUE",
//     "Sorcerer": "FALSE",
//     "Wizard": "FALSE",
//     "Untrained": "TRUE",
//     "Ability": "Str",
//     "ArmorCheck": "TRUE"
//   },
//   {
//     "Skill": "Craft",
//     "Barbarian": "TRUE",
//     "Bard": "TRUE",
//     "Cleric": "TRUE",
//     "Druid": "TRUE",
//     "Fighter": "TRUE",
//     "Monk": "TRUE",
//     "Paladin": "TRUE",
//     "Ranger": "TRUE",
//     "Rogue": "TRUE",
//     "Sorcerer": "TRUE",
//     "Wizard": "TRUE",
//     "Untrained": "TRUE",
//     "Ability": "Int",
//     "ArmorCheck": "FALSE"
//   },
//   {
//     "Skill": "Diplomacy",
//     "Barbarian": "FALSE",
//     "Bard": "TRUE",
//     "Cleric": "TRUE",
//     "Druid": "FALSE",
//     "Fighter": "FALSE",
//     "Monk": "FALSE",
//     "Paladin": "TRUE",
//     "Ranger": "FALSE",
//     "Rogue": "TRUE",
//     "Sorcerer": "FALSE",
//     "Wizard": "FALSE",
//     "Untrained": "TRUE",
//     "Ability": "Cha",
//     "ArmorCheck": "FALSE"
//   },
//   {
//     "Skill": "Disable Device",
//     "Barbarian": "FALSE",
//     "Bard": "FALSE",
//     "Cleric": "FALSE",
//     "Druid": "FALSE",
//     "Fighter": "FALSE",
//     "Monk": "FALSE",
//     "Paladin": "FALSE",
//     "Ranger": "FALSE",
//     "Rogue": "TRUE",
//     "Sorcerer": "FALSE",
//     "Wizard": "FALSE",
//     "Untrained": "FALSE",
//     "Ability": "Dex",
//     "ArmorCheck": "TRUE"
//   },
//   {
//     "Skill": "Disguise",
//     "Barbarian": "FALSE",
//     "Bard": "TRUE",
//     "Cleric": "FALSE",
//     "Druid": "FALSE",
//     "Fighter": "FALSE",
//     "Monk": "FALSE",
//     "Paladin": "FALSE",
//     "Ranger": "FALSE",
//     "Rogue": "TRUE",
//     "Sorcerer": "FALSE",
//     "Wizard": "FALSE",
//     "Untrained": "TRUE",
//     "Ability": "Cha",
//     "ArmorCheck": "FALSE"
//   },
//   {
//     "Skill": "Escape Artist",
//     "Barbarian": "FALSE",
//     "Bard": "TRUE",
//     "Cleric": "FALSE",
//     "Druid": "FALSE",
//     "Fighter": "FALSE",
//     "Monk": "TRUE",
//     "Paladin": "FALSE",
//     "Ranger": "FALSE",
//     "Rogue": "TRUE",
//     "Sorcerer": "FALSE",
//     "Wizard": "FALSE",
//     "Untrained": "TRUE",
//     "Ability": "Dex",
//     "ArmorCheck": "TRUE"
//   },
//   {
//     "Skill": "Fly",
//     "Barbarian": "FALSE",
//     "Bard": "FALSE",
//     "Cleric": "FALSE",
//     "Druid": "TRUE",
//     "Fighter": "FALSE",
//     "Monk": "FALSE",
//     "Paladin": "FALSE",
//     "Ranger": "FALSE",
//     "Rogue": "FALSE",
//     "Sorcerer": "TRUE",
//     "Wizard": "TRUE",
//     "Untrained": "TRUE",
//     "Ability": "Dex",
//     "ArmorCheck": "TRUE"
//   },
//   {
//     "Skill": "Handle Animal",
//     "Barbarian": "TRUE",
//     "Bard": "FALSE",
//     "Cleric": "FALSE",
//     "Druid": "TRUE",
//     "Fighter": "TRUE",
//     "Monk": "FALSE",
//     "Paladin": "TRUE",
//     "Ranger": "TRUE",
//     "Rogue": "FALSE",
//     "Sorcerer": "FALSE",
//     "Wizard": "FALSE",
//     "Untrained": "FALSE",
//     "Ability": "Cha",
//     "ArmorCheck": "FALSE"
//   },
//   {
//     "Skill": "Heal",
//     "Barbarian": "FALSE",
//     "Bard": "FALSE",
//     "Cleric": "TRUE",
//     "Druid": "TRUE",
//     "Fighter": "FALSE",
//     "Monk": "FALSE",
//     "Paladin": "TRUE",
//     "Ranger": "TRUE",
//     "Rogue": "FALSE",
//     "Sorcerer": "FALSE",
//     "Wizard": "FALSE",
//     "Untrained": "TRUE",
//     "Ability": "Wis",
//     "ArmorCheck": "FALSE"
//   },
//   {
//     "Skill": "Intimidate",
//     "Barbarian": "TRUE",
//     "Bard": "TRUE",
//     "Cleric": "FALSE",
//     "Druid": "FALSE",
//     "Fighter": "TRUE",
//     "Monk": "TRUE",
//     "Paladin": "FALSE",
//     "Ranger": "TRUE",
//     "Rogue": "TRUE",
//     "Sorcerer": "TRUE",
//     "Wizard": "FALSE",
//     "Untrained": "TRUE",
//     "Ability": "Cha",
//     "ArmorCheck": "FALSE"
//   },
//   {
//     "Skill": "Knowledge (arcana)",
//     "Barbarian": "FALSE",
//     "Bard": "TRUE",
//     "Cleric": "TRUE",
//     "Druid": "FALSE",
//     "Fighter": "FALSE",
//     "Monk": "FALSE",
//     "Paladin": "FALSE",
//     "Ranger": "FALSE",
//     "Rogue": "FALSE",
//     "Sorcerer": "TRUE",
//     "Wizard": "TRUE",
//     "Untrained": "FALSE",
//     "Ability": "Int",
//     "ArmorCheck": "FALSE"
//   },
//   {
//     "Skill": "Knowledge (dungeoneering)",
//     "Barbarian": "FALSE",
//     "Bard": "TRUE",
//     "Cleric": "FALSE",
//     "Druid": "FALSE",
//     "Fighter": "TRUE",
//     "Monk": "FALSE",
//     "Paladin": "FALSE",
//     "Ranger": "TRUE",
//     "Rogue": "TRUE",
//     "Sorcerer": "FALSE",
//     "Wizard": "TRUE",
//     "Untrained": "FALSE",
//     "Ability": "Int",
//     "ArmorCheck": "FALSE"
//   },
//   {
//     "Skill": "Knowledge (engineering)",
//     "Barbarian": "FALSE",
//     "Bard": "TRUE",
//     "Cleric": "FALSE",
//     "Druid": "FALSE",
//     "Fighter": "TRUE",
//     "Monk": "FALSE",
//     "Paladin": "FALSE",
//     "Ranger": "FALSE",
//     "Rogue": "FALSE",
//     "Sorcerer": "FALSE",
//     "Wizard": "TRUE",
//     "Untrained": "FALSE",
//     "Ability": "Int",
//     "ArmorCheck": "FALSE"
//   },
//   {
//     "Skill": "Knowledge (geography)",
//     "Barbarian": "FALSE",
//     "Bard": "TRUE",
//     "Cleric": "FALSE",
//     "Druid": "TRUE",
//     "Fighter": "FALSE",
//     "Monk": "FALSE",
//     "Paladin": "FALSE",
//     "Ranger": "TRUE",
//     "Rogue": "FALSE",
//     "Sorcerer": "FALSE",
//     "Wizard": "TRUE",
//     "Untrained": "FALSE",
//     "Ability": "Int",
//     "ArmorCheck": "FALSE"
//   },
//   {
//     "Skill": "Knowledge (history)",
//     "Barbarian": "FALSE",
//     "Bard": "TRUE",
//     "Cleric": "TRUE",
//     "Druid": "FALSE",
//     "Fighter": "FALSE",
//     "Monk": "TRUE",
//     "Paladin": "FALSE",
//     "Ranger": "FALSE",
//     "Rogue": "FALSE",
//     "Sorcerer": "FALSE",
//     "Wizard": "TRUE",
//     "Untrained": "FALSE",
//     "Ability": "Int",
//     "ArmorCheck": "FALSE"
//   },
//   {
//     "Skill": "Knowledge (local)",
//     "Barbarian": "FALSE",
//     "Bard": "TRUE",
//     "Cleric": "FALSE",
//     "Druid": "FALSE",
//     "Fighter": "FALSE",
//     "Monk": "FALSE",
//     "Paladin": "FALSE",
//     "Ranger": "FALSE",
//     "Rogue": "TRUE",
//     "Sorcerer": "FALSE",
//     "Wizard": "TRUE",
//     "Untrained": "FALSE",
//     "Ability": "Int",
//     "ArmorCheck": "FALSE"
//   },
//   {
//     "Skill": "Knowledge (nature)",
//     "Barbarian": "TRUE",
//     "Bard": "TRUE",
//     "Cleric": "FALSE",
//     "Druid": "TRUE",
//     "Fighter": "FALSE",
//     "Monk": "FALSE",
//     "Paladin": "FALSE",
//     "Ranger": "TRUE",
//     "Rogue": "FALSE",
//     "Sorcerer": "FALSE",
//     "Wizard": "TRUE",
//     "Untrained": "FALSE",
//     "Ability": "Int",
//     "ArmorCheck": "FALSE"
//   },
//   {
//     "Skill": "Knowledge (nobility)",
//     "Barbarian": "FALSE",
//     "Bard": "TRUE",
//     "Cleric": "TRUE",
//     "Druid": "FALSE",
//     "Fighter": "FALSE",
//     "Monk": "FALSE",
//     "Paladin": "TRUE",
//     "Ranger": "FALSE",
//     "Rogue": "FALSE",
//     "Sorcerer": "FALSE",
//     "Wizard": "TRUE",
//     "Untrained": "FALSE",
//     "Ability": "Int",
//     "ArmorCheck": "FALSE"
//   },
//   {
//     "Skill": "Knowledge (planes)",
//     "Barbarian": "FALSE",
//     "Bard": "TRUE",
//     "Cleric": "TRUE",
//     "Druid": "FALSE",
//     "Fighter": "FALSE",
//     "Monk": "FALSE",
//     "Paladin": "FALSE",
//     "Ranger": "FALSE",
//     "Rogue": "FALSE",
//     "Sorcerer": "FALSE",
//     "Wizard": "TRUE",
//     "Untrained": "FALSE",
//     "Ability": "Int",
//     "ArmorCheck": "FALSE"
//   },
//   {
//     "Skill": "Knowledge (religion)",
//     "Barbarian": "FALSE",
//     "Bard": "TRUE",
//     "Cleric": "TRUE",
//     "Druid": "FALSE",
//     "Fighter": "FALSE",
//     "Monk": "TRUE",
//     "Paladin": "TRUE",
//     "Ranger": "FALSE",
//     "Rogue": "FALSE",
//     "Sorcerer": "FALSE",
//     "Wizard": "TRUE",
//     "Untrained": "FALSE",
//     "Ability": "Int",
//     "ArmorCheck": "FALSE"
//   },
//   {
//     "Skill": "Linguistics",
//     "Barbarian": "FALSE",
//     "Bard": "TRUE",
//     "Cleric": "TRUE",
//     "Druid": "FALSE",
//     "Fighter": "FALSE",
//     "Monk": "FALSE",
//     "Paladin": "FALSE",
//     "Ranger": "FALSE",
//     "Rogue": "TRUE",
//     "Sorcerer": "FALSE",
//     "Wizard": "TRUE",
//     "Untrained": "FALSE",
//     "Ability": "Int",
//     "ArmorCheck": "FALSE"
//   },
//   {
//     "Skill": "Perception",
//     "Barbarian": "TRUE",
//     "Bard": "TRUE",
//     "Cleric": "FALSE",
//     "Druid": "TRUE",
//     "Fighter": "FALSE",
//     "Monk": "TRUE",
//     "Paladin": "FALSE",
//     "Ranger": "TRUE",
//     "Rogue": "TRUE",
//     "Sorcerer": "FALSE",
//     "Wizard": "FALSE",
//     "Untrained": "TRUE",
//     "Ability": "Wis",
//     "ArmorCheck": "FALSE"
//   },
//   {
//     "Skill": "Perform",
//     "Barbarian": "FALSE",
//     "Bard": "TRUE",
//     "Cleric": "FALSE",
//     "Druid": "FALSE",
//     "Fighter": "FALSE",
//     "Monk": "TRUE",
//     "Paladin": "FALSE",
//     "Ranger": "FALSE",
//     "Rogue": "TRUE",
//     "Sorcerer": "FALSE",
//     "Wizard": "FALSE",
//     "Untrained": "TRUE",
//     "Ability": "Cha",
//     "ArmorCheck": "FALSE"
//   },
//   {
//     "Skill": "Profession",
//     "Barbarian": "FALSE",
//     "Bard": "TRUE",
//     "Cleric": "TRUE",
//     "Druid": "TRUE",
//     "Fighter": "TRUE",
//     "Monk": "TRUE",
//     "Paladin": "TRUE",
//     "Ranger": "TRUE",
//     "Rogue": "TRUE",
//     "Sorcerer": "TRUE",
//     "Wizard": "TRUE",
//     "Untrained": "FALSE",
//     "Ability": "Wis",
//     "ArmorCheck": "FALSE"
//   },
//   {
//     "Skill": "Ride",
//     "Barbarian": "TRUE",
//     "Bard": "FALSE",
//     "Cleric": "FALSE",
//     "Druid": "TRUE",
//     "Fighter": "TRUE",
//     "Monk": "TRUE",
//     "Paladin": "TRUE",
//     "Ranger": "TRUE",
//     "Rogue": "FALSE",
//     "Sorcerer": "FALSE",
//     "Wizard": "FALSE",
//     "Untrained": "TRUE",
//     "Ability": "Dex",
//     "ArmorCheck": "TRUE"
//   },
//   {
//     "Skill": "Sense Motive",
//     "Barbarian": "FALSE",
//     "Bard": "TRUE",
//     "Cleric": "TRUE",
//     "Druid": "FALSE",
//     "Fighter": "FALSE",
//     "Monk": "TRUE",
//     "Paladin": "TRUE",
//     "Ranger": "FALSE",
//     "Rogue": "TRUE",
//     "Sorcerer": "FALSE",
//     "Wizard": "FALSE",
//     "Untrained": "TRUE",
//     "Ability": "Wis",
//     "ArmorCheck": "FALSE"
//   },
//   {
//     "Skill": "Sleight of Hand",
//     "Barbarian": "FALSE",
//     "Bard": "TRUE",
//     "Cleric": "FALSE",
//     "Druid": "FALSE",
//     "Fighter": "FALSE",
//     "Monk": "FALSE",
//     "Paladin": "FALSE",
//     "Ranger": "FALSE",
//     "Rogue": "TRUE",
//     "Sorcerer": "FALSE",
//     "Wizard": "FALSE",
//     "Untrained": "FALSE",
//     "Ability": "Dex",
//     "ArmorCheck": "TRUE"
//   },
//   {
//     "Skill": "Spellcraft",
//     "Barbarian": "FALSE",
//     "Bard": "TRUE",
//     "Cleric": "TRUE",
//     "Druid": "TRUE",
//     "Fighter": "FALSE",
//     "Monk": "FALSE",
//     "Paladin": "TRUE",
//     "Ranger": "TRUE",
//     "Rogue": "FALSE",
//     "Sorcerer": "TRUE",
//     "Wizard": "TRUE",
//     "Untrained": "FALSE",
//     "Ability": "Int",
//     "ArmorCheck": "FALSE"
//   },
//   {
//     "Skill": "Stealth",
//     "Barbarian": "FALSE",
//     "Bard": "TRUE",
//     "Cleric": "FALSE",
//     "Druid": "FALSE",
//     "Fighter": "FALSE",
//     "Monk": "TRUE",
//     "Paladin": "FALSE",
//     "Ranger": "TRUE",
//     "Rogue": "TRUE",
//     "Sorcerer": "FALSE",
//     "Wizard": "FALSE",
//     "Untrained": "TRUE",
//     "Ability": "Dex",
//     "ArmorCheck": "TRUE"
//   },
//   {
//     "Skill": "Survival",
//     "Barbarian": "TRUE",
//     "Bard": "FALSE",
//     "Cleric": "FALSE",
//     "Druid": "TRUE",
//     "Fighter": "TRUE",
//     "Monk": "FALSE",
//     "Paladin": "FALSE",
//     "Ranger": "TRUE",
//     "Rogue": "FALSE",
//     "Sorcerer": "FALSE",
//     "Wizard": "FALSE",
//     "Untrained": "TRUE",
//     "Ability": "Wis",
//     "ArmorCheck": "FALSE"
//   },
//   {
//     "Skill": "Swim",
//     "Barbarian": "TRUE",
//     "Bard": "FALSE",
//     "Cleric": "FALSE",
//     "Druid": "TRUE",
//     "Fighter": "TRUE",
//     "Monk": "TRUE",
//     "Paladin": "FALSE",
//     "Ranger": "TRUE",
//     "Rogue": "TRUE",
//     "Sorcerer": "FALSE",
//     "Wizard": "FALSE",
//     "Untrained": "TRUE",
//     "Ability": "Str",
//     "ArmorCheck": "TRUE"
//   },
//   {
//     "Skill": "Use Magic Device",
//     "Barbarian": "FALSE",
//     "Bard": "TRUE",
//     "Cleric": "FALSE",
//     "Druid": "FALSE",
//     "Fighter": "FALSE",
//     "Monk": "FALSE",
//     "Paladin": "FALSE",
//     "Ranger": "FALSE",
//     "Rogue": "TRUE",
//     "Sorcerer": "TRUE",
//     "Wizard": "FALSE",
//     "Untrained": "FALSE",
//     "Ability": "Cha",
//     "ArmorCheck": "FALSE"
//   }
// ]
